app/base/models.py
# -*- encoding: utf-8 -*-

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from app import db, login_manager

from app.base.util import hash_pass


class User(db.Model, UserMixin):
	__tablename__ = 'avrentallogin'
	
	id = Column(Integer, primary_key=True)
	username = Column(String, unique=True)
	email = Column(String, unique=True)
	password = Column(Binary)
	role = Column(String)
	firstname = Column(String)
	lastname =  Column(String)
	address =  Column(String)
	city =  Column(String)
	zip =  Column(String)
	houseno = Column(String)
	dob =  Column(String)
	gender =  Column(String)
	phonenumber =  Column(String)
	amount  = Column(Integer)
	car = relationship('Car', backref='owner', lazy='dynamic', primaryjoin='User.id == Car.user_id')
	
	def __init__(self, **kwargs):
		for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
			if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
				value = value[0]
			
			if property == 'password':
				value = hash_pass(value)  # we need bytes here (not plain str)
			
			setattr(self, property, value)
	def __repr__(self):
		return str(self.username)


class Car(db.Model):
	__tablename__ = 'avrentalcars'
	
	id = Column(Integer, primary_key=True)
	user_id = Column(Integer, ForeignKey('avrentallogin.id'))
	carmodel = Column(String)
	carNo = Column(String)
	carcolor = Column(String)
	cartype = Column(String)
	active = Column(String)
	ride = relationship('Ride', backref='ride', lazy='dynamic', primaryjoin='Car.id == Ride.car_id')
	
	def __repr__(self):
		return '<Carmodel: {}'.format(self.carmodel)


class Ride(db.Model):
	__tablename__ = 'avrentalrides'
	
	id = Column(Integer, primary_key=True)
	car_id = Column(Integer, ForeignKey('avrentalcars.id'))
	source = Column(String)
	destination = Column(String)
	payment = Column(String)
	userId = Column(Integer)
	trip_status = Column(String)
	
	def __repr__(self):
		return '<RideDetails: {}'.format(self.source)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()


@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField, RadioField, SelectField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])
    role     = SelectField('Role'       , id='role'            , validators=[DataRequired()], choices=[('', 'View roles'), ('owner', 'Car owner'), ('user', 'Car user'), ('admin', 'System administrator')], render_kw={'onchange': 'enable_fn()'})
    carmodel = TextField('carmodel'     , id='carmodel'        , validators=[DataRequired()], render_kw={'disabled':'True'})
    carNo = TextField('carNo' , id='carNo', validators=[DataRequired()], render_kw={'disabled':'True'})
    carcolor = TextField('carcolor' , id='carcolor', validators=[DataRequired()], render_kw={'disabled':'True'})
    cartype = SelectField('cartype', id='cartype', choices=[('', 'View car types'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Limousine', 'Limousine')], render_kw={'disabled':'True'})

app/base/__init__.py
# -*- encoding: utf-8 -*-

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User, Car

from app.base.util import verify_pass
# from app.helpers.mailer import *


@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))


## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:

        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()

        # Check the password
        if user and verify_pass(password, user.password):
            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template('accounts/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template('accounts/login.html',
                               form=login_form)
    if current_user.role == 'admin':
        return redirect(url_for('home_blueprint.dashboardadmin'))
    elif current_user.role == 'owner':
        return redirect(url_for('home_blueprint.dashboardowner'))
    else:
        return redirect(url_for('home_blueprint.dashboard'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username = request.form['username']
        email = request.form['email']

        # Check usename exists
        user = User.query.filter_by(username=username).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Username already registered',
                                   success=False,
                                   form=create_account_form)

        # Check email exists
        user = User.query.filter_by(email=email).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Email already registered',
                                   success=False,
                                   form=create_account_form)

        # else we can create the user
        user = User(
            username=request.form['username'],
            password=request.form['password'],
            email=request.form['email'],
            role=request.form['role'],
        )
        db.session.add(user)
        db.session.commit()

        if request.form['role'] == 'owner':
            car = Car(
                owner=user,
                carmodel=request.form['carmodel'],
                carNo=request.form['carNo'],
                carcolor=request.form['carcolor'],
                cartype=request.form['cartype'],
                active='false'
            )
            db.session.add(car)
            db.session.commit()
            # sendmail(subject="Registration for Flask Admin Boilerplate", sender="Flask Admin Boilerplate",
            #          recipient=email, body="You successfully registered on Flask Admin Boilerplate")
            # print("Done")
        return render_template('accounts/register.html',
                               msg='User created please <a href="/login">login</a>',
                               success=True,
                               form=create_account_form)

    else:
        return render_template('accounts/register.html', form=create_account_form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))


## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('page-403.html'), 403


@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('page-403.html'), 403


@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404


@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('page-500.html'), 500

app/base/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <!-- Section -->
        <section class="d-flex align-items-center my-5 mt-lg-6 mb-lg-5">
            <div class="container">
                <div class="row justify-content-center form-bg-image" data-background-lg="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <img src="{{url_for('static', filename='assets/img/av_logo.jpg')}}" alt=logo width="130" height="110">
                                <h1 class="mb-0 h3">
                                    AVRental - Login
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Add your credentials
                                    {% endif %}                                     
                                </p>                                 
                            </div>

                            <form method="post" action="" class="mt-4">
                                
                                {{ form.hidden_tag() }}

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Username</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1"><span class="fas fa-user-circle"></span></span>
                                        {{ form.username(placeholder="Username", class="form-control") }}
                                    </div>  
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Your Password</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2"><span class="fas fa-unlock-alt"></span></span>
                                            {{ form.password(placeholder="Password", class="form-control", type="password") }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->
                                    <div class="d-flex justify-content-between align-items-top mb-4">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="remember">
                                            <label class="form-check-label mb-0" for="remember">
                                              Remember me
                                            </label>
                                        </div>
                                        <!-- <div><a href="./forgot-password.html" class="small text-right">Lost password?</a></div> -->
                                    </div>
                                </div>
                                <div class="d-grid">
                                    <button type="submit" name="login" class="btn btn-dark">Login</button>
                                </div>
                            </form>

                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="fw-normal">
                                    Not registered?
                                    <a href="{{ url_for('base_blueprint.register') }}" class="fw-bold">Create account</a>
                                </span>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Sign Up {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="d-flex align-items-center my-5 mt-lg-6 mb-lg-5">
            <div class="container">
                <div class="row justify-content-center form-bg-image" data-background-lg="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="mb-4 mb-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <img src="{{url_for('static', filename='assets/img/av_logo.jpg')}}" alt=logo width="130" height="110">
                                <h1 class="mb-0 h3">
                                    Create an account
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Add your credentials
                                    {% endif %}                                     
                                </p> 
                            </div>

                            <form method="post" action="">
                            
                                {{ form.hidden_tag() }}

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Username</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon3"><span class="fas fa-user-shield"></span></span>
                                        {{ form.username(placeholder="Username", class="form-control") }}
                                    </div>  
                                </div>

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Your Email</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon3"><span class="fas fa-envelope"></span></span>
                                        {{ form.email(placeholder="Email", class="input form-control", type="email") }}
                                    </div>  
                                </div>
                                <!-- End of Form -->

                                <!-- End of Form -->
                                <div class="form-group">

                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Your Password</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon4"><span class="fas fa-unlock-alt"></span></span>
                                            {{ form.password(placeholder="Password", class="form-control", type="password") }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->
                                    
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label class="my-1 me-2" for="role">Select your Role</label>
                                        {{form.role(class="form-select")}}
                                    </div>
                                    <!-- End of Form -->

                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="carmodel">Your Car Model</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon3"><span class="fas fa-car"></span></span>
                                            {{ form.carmodel(placeholder="Car Model", class="form-control") }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->

                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="carNo">Your Car Number</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon3"><span class="fas fa-id-badge"></span></span>
                                            {{ form.carNo(placeholder="Car No.", class="form-control") }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->

                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="carcolor">Your Car Color</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon3"><span class="fas fa-swatchbook"></span></span>
                                            {{ form.carcolor(placeholder="Car Color", class="form-control") }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->

                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label class="my-1 me-2" for="role">Select your Car Type</label>
                                        {{form.cartype(class="form-select")}}
                                    </div>
                                    <!-- End of Form -->

                                    <div class="d-flex justify-content-between align-items-top mb-4" style="margin-top: 30px;">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="remember">
                                            <label class="form-check-label mb-0" for="remember">
                                              I agree to the terms and conditions
                                            </label>
                                        </div>
                                    </div>                                  
                                </div>
                                <div class="d-grid">
                                    <button type="submit" name="register" class="btn btn-dark">Sign Up</button>
                                </div>
                            </form>
                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="fw-normal">
                                    Already registered?
                                    <a href="{{ url_for('base_blueprint.login') }}" class="fw-bold">Login here</a>
                                </span>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/includes/footer.html
<footer class="footer section py-5">
        <div class="row">
            <div class="col-12 col-lg-6 mb-4 mb-lg-0">
                <p class="mb-0 text-center text-xl-left">
                    &copy; <a class="text-primary fw-normal" href="" target="_blank">AVRentals</a>
                - Coded by <a href="" target="_blank">Team 9</a>
                </p>
            </div>

            <!-- <div class="col-12 col-lg-6">
                <ul class="list-inline list-group-flush list-group-borderless text-center text-xl-right mb-0">
                    <li class="list-inline-item px-0 px-sm-2">
                        <a target="_blank" 
                           href="">AVRentals</a>
                    </li>
                </ul> -->
            </div>
        </div>
    </footer>
    

app/base/templates/includes/navigation.html
    <nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
        <div class="container-fluid px-0">
          <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
            <div class="d-flex align-items-center">
              <!-- Search form -->
              <!-- <form class="navbar-search form-inline" id="navbar-search-main">
                <div class="input-group input-group-merge search-bar">
                    <span class="input-group-text" id="topbar-addon"><span class="fas fa-search"></span></span>
                    <input type="text" class="form-control" id="topbarInputIconLeft" placeholder="Search" aria-label="Search" aria-describedby="topbar-addon">
                </div>
              </form> -->
            </div>
            <!-- Navbar links -->
            <ul class="navbar-nav align-items-center">
              <li class="nav-item dropdown">
                <a class="nav-link text-dark me-lg-3 icon-notifications dropdown-toggle" data-unread-notifications="true" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="icon icon-sm">
                    <span class="fas fa-bell bell-shake"></span>
                    <span class="icon-badge rounded-circle unread-notifications"></span>
                  </span>
                </a>
                <!-- <div class="dropdown-menu dashboard-dropdown dropdown-menu-lg dropdown-menu-center mt-2 py-0">
                  <div class="list-group list-group-flush">
                    <a href="#" class="text-center text-primary fw-bold border-bottom border-light py-3">Notifications</a>
                    <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                      <div class="row align-items-center">
                          <div class="col-auto">
                            <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-1.jpg" class="user-avatar lg-avatar rounded-circle">
                          </div>
                          <div class="col ps-0 ms-2">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                  <h4 class="h6 mb-0 text-small">Jose Leos</h4>
                                </div>
                                <div class="text-end">
                                  <small class="text-danger">a few moments ago</small>
                                </div>
                            </div>
                            <p class="font-small mt-1 mb-0">Added you to an event "Project stand-up" tomorrow at 12:30 AM.</p>
                          </div>
                      </div>
                    </a>
                    <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                      <div class="row align-items-center">
                          <div class="col-auto">
                            <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-2.jpg" class="user-avatar lg-avatar rounded-circle">
                          </div>
                          <div class="col ps-0 ms-2">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                  <h4 class="h6 mb-0 text-small">Neil Sims</h4>
                                </div>
                                <div class="text-end">
                                  <small class="text-danger">2 hrs ago</small>
                                </div>
                            </div>
                            <p class="font-small mt-1 mb-0">You've been assigned a task for "Awesome new project".</p>
                          </div>
                      </div>
                    </a>
                    <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                      <div class="row align-items-center">
                          <div class="col-auto">
                            <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-3.jpg" class="user-avatar lg-avatar rounded-circle">
                          </div>
                          <div class="col ps-0 m-2">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                  <h4 class="h6 mb-0 text-small">Roberta Casas</h4>
                                </div>
                                <div class="text-end">
                                  <small>5 hrs ago</small>
                                </div>
                            </div>
                            <p class="font-small mt-1 mb-0">Tagged you in a document called "First quarter financial plans",</p>
                          </div>
                      </div>
                    </a>
                    <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                      <div class="row align-items-center">
                          <div class="col-auto">
                            <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-4.jpg" class="user-avatar lg-avatar rounded-circle">
                          </div>
                          <div class="col ps-0 ms-2">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                  <h4 class="h6 mb-0 text-small">Joseph Garth</h4>
                                </div>
                                <div class="text-end">
                                  <small>1 d ago</small>
                                </div>
                            </div>
                            <p class="font-small mt-1 mb-0">New message: "Hey, what's up? All set for the presentation?"</p>
                          </div>
                      </div>
                    </a>
                    <a href="#" class="list-group-item list-group-item-action border-bottom border-light">
                      <div class="row align-items-center">
                          <div class="col-auto">
                            <img alt="Image placeholder" src="/static/assets/img/team/profile-picture-5.jpg" class="user-avatar lg-avatar rounded-circle">
                          </div>
                          <div class="col ps-0 ms-2">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                  <h4 class="h6 mb-0 text-small">Bonnie Green</h4>
                                </div>
                                <div class="text-end">
                                  <small>2 hrs ago</small>
                                </div>
                            </div>
                            <p class="font-small mt-1 mb-0">New message: "We need to improve the UI/UX for the landing page."</p>
                          </div>
                      </div>
                    </a>
                    <a href="#" class="dropdown-item text-center text-primary fw-bold rounded-bottom py-3">View all</a>
                  </div>
                </div> -->
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <div class="media d-flex align-items-center">
                    <img class="user-avatar md-avatar rounded-circle" alt="Image placeholder" src="/static/assets/img/team/profile-picture-3.jpg">
                    <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
                      <span class="mb-0 font-small fw-bold">
                        Current User: <strong>{{ current_user.username }}</strong>
                      </span>
                    </div>
                  </div>
                </a>
                <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-0">
                    <a class="dropdown-item rounded-top fw-bold" href="{{ url_for('home_blueprint.settings') }}">
                      <span class="far fa-user-circle"></span>My Profile</a>
                    <!-- <a class="dropdown-item fw-bold" href="/settings.html"><span class="fas fa-cog"></span>Settings</a> -->
                    <div role="separator" class="dropdown-divider my-0"></div>
                    <a class="dropdown-item rounded-bottom fw-bold" href="{{ url_for('base_blueprint.logout') }}">
                      <span class="fas fa-sign-out-alt text-danger"></span>Logout</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
    </nav>
    